replicaCount: 1

image:
  repository: rabbitmq
  tag: "4.1.0-management"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

auth:
  username: magefleet
  password: changeme
  erlangCookie: secretcookie
  # Use an existing secret instead of creating one
  existingSecret: ""
  existingSecretPasswordKey: "rabbitmq-password"
  existingSecretErlangCookieKey: "rabbitmq-erlang-cookie"

service:
  type: ClusterIP
  port: 5672
  managementPort: 15672

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podSecurityContext:
  fsGroup: 999

securityContext:
  runAsUser: 999
  runAsNonRoot: true

livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 30
  timeoutSeconds: 20
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 20
  failureThreshold: 3
  successThreshold: 1

metrics:
  enabled: false
  port: 15692

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: rabbitmq.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
