apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: amqp
    port: {{ .Values.service.port }}
    targetPort: amqp
    protocol: TCP
  - name: management
    port: {{ .Values.service.managementPort }}
    targetPort: management
    protocol: TCP
  {{- if .Values.metrics.enabled }}
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
  {{- end }}
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-headless
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: amqp
    port: {{ .Values.service.port }}
    targetPort: amqp
    protocol: TCP
  - name: management
    port: {{ .Values.service.managementPort }}
    targetPort: management
    protocol: TCP
  - name: epmd
    port: 4369
    targetPort: epmd
    protocol: TCP
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
